include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    must_be_immutable: ignore
    deprecated_member_use: ignore
    unused_import: ignore
    unused_local_variable: ignore
    strict_top_level_inference: ignore

linter:
  rules:
    use_key_in_widget_constructors: False
    constant_identifier_names: False
    prefer_const_constructors: False
    use_super_parameters: False
    non_constant_identifier_names: False
    unnecessary_overrides: False
    annotate_overrides: False
    overridden_fields: False
    sized_box_for_whitespace: False
    depend_on_referenced_packages: False
    avoid_print: False
    file_names: False
    prefer_const_literals_to_create_immutables: False