// 
// AUTO GENERATE FILE, DONT MODIFY!!
// ignored: 
//.g.dart
//.gen.dart
export 'package:templax/core/constants/session_keys.dart';
export 'package:templax/core/constants/color_constant.dart';
export 'package:templax/core/constants/app_constant.dart';
export 'package:templax/core/utils/helpers.dart';
export 'package:templax/core/utils/preferences.dart';
export 'package:templax/core/utils/size_utils.dart';
export 'package:templax/core/utils/custom_log.dart';
export 'package:templax/core/utils/custom_image_view.dart';
export 'package:templax/core/utils/validator.dart';
export 'package:templax/core/utils/validation_functions.dart';
export 'package:templax/core/utils/init_instance.dart';
export 'package:templax/core/utils/init_binding.dart';
export 'package:templax/core/theme/app_theme.dart';
export 'package:templax/core/widgets/back_button.dart';
export 'package:templax/core/widgets/form/custom_phone_number.dart';
export 'package:templax/core/widgets/form/custom_text_form_field.dart';
export 'package:templax/core/widgets/form/custom_switch.dart';
export 'package:templax/core/widgets/form/custom_checkbox.dart';
export 'package:templax/core/widgets/form/custom_icon_button.dart';
export 'package:templax/core/widgets/form/custom_drop_down.dart';
export 'package:templax/core/widgets/form/custom_radio_button.dart';
export 'package:templax/core/widgets/loader.dart';
export 'package:templax/core/widgets/spacing.dart';
export 'package:templax/core/widgets/custom_button.dart';
export 'package:templax/core/widgets/snackbar.dart';
export 'package:templax/core/widgets/footer.dart';
export 'package:templax/Models/0x/error_reponse.dart';
export 'package:templax/Models/0x/selection_popup_model.dart';
export 'package:templax/Models/auth/req_auth.dart';
export 'package:templax/Models/auth/res_auth.dart';
export 'package:templax/main.dart';
export 'package:templax/api/config/base.dart';
export 'package:templax/api/config/api_endpoints.dart';
export 'package:templax/api/modules/auth_provider.dart';
export 'package:templax/api/interceptor/auth_interceptor.dart';
export 'package:templax/api/interceptor/response_interceptor.dart';
export 'package:templax/api/interceptor/request_interceptor.dart';
export 'package:templax/controllers/splash/binding_splash.dart';
export 'package:templax/controllers/splash/controller_splash.dart';
export 'package:templax/controllers/auth/controller_other.dart';
export 'package:templax/controllers/auth/binding_other.dart';
export 'package:templax/views/auth/auth.dart';
export 'package:templax/views/splash.dart';
export 'package:templax/routes/app_pages.dart';